### ISSUE TITLE
Add Dart implementation for Singleton pattern

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#6]

**Comment by KaiKitKobold** [comment]
Hello @ash-teach, Can I be assigned to this issue and #5? Unless Dawson on slack wishes to work on this language then I can do #5, and he can do #3 
Since this is my primary language of choice, I can also help with JavaScript #3 If the current assignee allows (I.E I can help with any aspect if it isn't closed by the time I implement my current patterns.

**Comment by ash-teach** [comment]
I've assigned you to this issue, @KaiKitKobold. We have two working on #3 already, so that might be enough for now. However, I do recommend that you subscribe to notifications on #3 if you're interested in supporting (by pressing the Subscribe button on the right sidebar in the issue description) that way you'll be able to support if need be. 

Let's leave #5 open for now, and see if anyone else is interested in grabbing it. If you finish this task and #5 is still open then we can assign it to you.

**Comment by KaiKitKobold** [comment]
Hello @ash-teach 
 I have finished this implementation, And since the pull request wasn't pulled yesterday, It is now in the updated version of #42, so committing this will (Hopefully) Fix both problems. 

I will most likely not contribute to the internal community for a while (Until maybe next week), Since I wish to prioritize the internal community and Research and Reflection journal.

**Comment by ash-teach** [comment]
Closed by #42
